name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        name: Tests
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          -
            name: Setup
            uses: actions/setup-go@v4
            with:
              go-version: '>=1.21'

          - 
            name: Test
            run: go test ./...